[package]
name = "cargo-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20 = "0.9.0"
rand = "0.8"
clap = { version = "3.2.16", features = ["derive"] }
cargo_metadata = "0.15.0"
brotli = "3.3.4"
colour = "0.6.0"
object = { version = "0.29.0", features = ["write"] }